title: SmartSpend
email: ""
description: "Personal finance and budgeting site for SmartSpend"
baseurl: "/smartspend-app" # the subpath of your site
url: "https://GDev1024.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
exclude:
  - "node_modules"

# Enable future collections and reading time (optional)
future: true
reading_time: true

# Build settings
paginate: 5
paginate_path: /page:num/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"